# Generated by Django 4.2.30 on 2026-09-09 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_lessons', models.JSONField(default=list, help_text='List of completed lesson IDs')),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('certificate_url', models.URLField(blank=True, max_length=500)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('estimated_hours', models.PositiveIntegerField(default=4)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('content_body', models.TextField(help_text='Lesson content in markdown')),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('worksheet_download_url', models.URLField(blank=True, help_text='Offline study PDF worksheet', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='MentorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areas_of_expertise', models.CharField(help_text='e.g. Mathematics, Python, Career Guidance', max_length=255)),
                ('highest_qualification', models.CharField(max_length=150)),
                ('current_employer_or_school', models.CharField(blank=True, max_length=200)),
                ('linkedin_or_portfolio', models.URLField(blank=True, max_length=500)),
                ('id_document_url', models.URLField(blank=True, help_text='Secure S3 URL for background check', max_length=500)),
                ('background_check_reference', models.CharField(blank=True, help_text='Checkr API Verification ID', max_length=100)),
                ('weekly_availability_hours', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved / Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_recurring', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Mentor availabilities',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_topic', models.CharField(help_text='e.g. Algebra 1, Python Functions, Resume Review', max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('requested', 'Session Requested'), ('scheduled', 'Confirmed & Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='requested', max_length=20)),
                ('meeting_link', models.URLField(blank=True, help_text='Jitsi, Zoom or Google Meet URL', max_length=500)),
                ('feedback_notes', models.TextField(blank=True, help_text='Post-session progress notes by mentor')),
                ('learner_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('worksheet_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PolicyBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('abstract', models.TextField()),
                ('authors', models.CharField(default='TIIPE Research Working Group', max_length=255)),
                ('research_area', models.CharField(help_text='e.g. Educational Equity, Health Disparities', max_length=150)),
                ('doi_or_reference', models.CharField(blank=True, max_length=150)),
                ('pdf_download_url', models.URLField(max_length=500)),
                ('citation_text', models.TextField(blank=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('category', models.CharField(choices=[('education_tutoring', 'Academic Tutoring & Mentorship'), ('workforce_development', 'Workforce Development & Digital Literacy'), ('public_health', 'Public Health Education & Maternal Literacy'), ('civic_engagement', 'Civic Engagement & Outreach'), ('community_research', 'Community-Based Research')], default='education_tutoring', max_length=50)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('impact_goal', models.CharField(blank=True, help_text="e.g. 'Empower 1,000 students in 2026'", max_length=255)),
                ('target_audience', models.CharField(blank=True, max_length=255)),
                ('cover_image_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PublicHealthResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('maternal_health', 'Maternal & Child Health Literacy'), ('disease_prevention', 'Chronic Disease & Infection Prevention'), ('nutrition_wellness', 'Community Nutrition & Wellness'), ('mental_health', 'Mental Health & Resilience')], default='maternal_health', max_length=40)),
                ('description', models.TextField()),
                ('target_group', models.CharField(blank=True, help_text='e.g. Expecting Mothers, Seniors, Youth', max_length=150)),
                ('file_download_url', models.URLField(max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
