# Generated by Django 4.2.30 on 2026-09-09 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tiipe_lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipsession',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorshipsession',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorshipsession',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='tiipe_lms.program'),
        ),
        migrations.AddField(
            model_name='mentoravailability',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='tiipe_lms.learningmodule'),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='tiipe_lms.program'),
        ),
        migrations.AddField(
            model_name='learnerprogress',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learnerprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_progress', to='tiipe_lms.learningmodule'),
        ),
        migrations.AlterUniqueTogether(
            name='learnerprogress',
            unique_together={('learner', 'module')},
        ),
    ]
