# Generated by Django 4.2.30 on 2026-09-09 07:10

import apps.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.files.models.get_tenant_upload_path)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('access_level', models.CharField(choices=[('public', 'Public - All Visitors'), ('mentor_only', 'Verified Mentors Only'), ('learner_only', 'Registered Learners Only'), ('client_only', 'Client Accounts Only'), ('admin_only', 'Administrators Only')], default='public', max_length=20)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.files.models.get_tenant_upload_path)),
                ('file_type', models.CharField(choices=[('image', 'Image File (PNG, JPG, WebP, SVG)'), ('audio', 'Audio File (MP3, WAV, AAC)'), ('video', 'Video File (MP4, WebM)'), ('document', 'PDF Document / Worksheet'), ('other', 'Other Media Asset')], default='image', max_length=20)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
