# Generated by Django 4.2.30 on 2026-09-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(help_text="e.g. 'welcome_email', 'donation_receipt'", max_length=100, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField(help_text='HTML template with {{ placeholders }}')),
                ('body_plain', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('channel', models.CharField(choices=[('email', 'Email (SendGrid/SMTP)'), ('push', 'Push Notification (Firebase Cloud Messaging)'), ('sms', 'SMS (Twilio)'), ('in_app', 'In-App Alert')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Dispatch'), ('sent', 'Sent Successfully'), ('failed', 'Dispatch Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushDeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'Apple iOS Device'), ('android', 'Google Android Device'), ('web', 'Web Browser Push')], default='android', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
