# Generated by Django 4.2.30 on 2026-09-09 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True, help_text='Short bio or background summary')),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('background_check_status', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Pending Verification'), ('verified', 'Verified / Cleared'), ('rejected', 'Rejected / Ineligible')], default='not_applicable', max_length=30)),
                ('background_check_date', models.DateTimeField(blank=True, null=True)),
                ('is_minor', models.BooleanField(default=False, help_text='COPPA compliance flag for youth under 18')),
                ('parental_consent_verified', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, default='United States', max_length=100)),
                ('state_or_city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Tenant Administrator'), ('staff', 'Tenant Staff / Editor'), ('mentor', 'TIIPE Verified Mentor / Volunteer'), ('learner', 'TIIPE Learner / Student'), ('donor', 'TIIPE Donor / Supporter'), ('community_partner', 'Community Partner / School'), ('client_lead', 'Novatrix Client / Decision-Maker'), ('training_student', 'Novatrix Training Participant'), ('corporate_buyer', 'Novatrix Corporate Training Buyer'), ('support_client', 'Novatrix Support Client')], default='learner', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.clienttenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('user', 'tenant', 'role')},
            },
        ),
    ]
