# Generated by Django 4.2.30 on 2026-09-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttenant',
            name='brand_type',
            field=models.CharField(choices=[('public', 'Public Master Routing Gateway'), ('tiipe', 'The Impact Institute for Public Education (Parent)'), ('novatrix', 'Novatrix Technology & Workforce (Subsidiary)')], default='public', max_length=30),
        ),
    ]
