# Generated by Django 4.2.30 on 2026-09-09 07:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapabilityDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(default='Corporate Capability Statement', max_length=100)),
                ('file_url', models.URLField(max_length=500)),
                ('file_size_kb', models.PositiveIntegerField(default=500)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndustrySolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('overview', models.TextField()),
                ('common_challenges', models.TextField()),
                ('sample_solutions', models.JSONField(default=list, help_text='List of solutions tailored to this industry')),
                ('compliance_disclaimer', models.CharField(blank=True, max_length=255)),
                ('icon_name', models.CharField(blank=True, max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('client_name', models.CharField(help_text='Client or Product Name (e.g. TIIPE Digital Platform)', max_length=150)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('delivered', 'Delivered & Verified'), ('in_development', 'In Active Development'), ('concept', 'Product Concept / Blueprint')], default='in_development', max_length=30)),
                ('challenge', models.TextField()),
                ('approach', models.TextField()),
                ('solution', models.TextField()),
                ('technology_stack', models.JSONField(default=list, help_text="['Django', 'React', 'PostgreSQL', 'Flutter']")),
                ('training_and_adoption', models.TextField(blank=True, help_text='Training provided to client staff')),
                ('outcomes_achieved', models.TextField(blank=True)),
                ('demo_url', models.URLField(blank=True, max_length=500)),
                ('cover_image_url', models.URLField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Project case studies',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_or_whatsapp', models.CharField(max_length=50)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('service_required', models.CharField(choices=[('custom_software', 'Custom Software Development'), ('system_implementation', 'System Implementation & Integration'), ('systems_integration', 'Systems Integration & APIs'), ('support_maintenance', 'Support & Maintenance'), ('other', 'Other Strategic Consultation')], default='custom_software', max_length=40)),
                ('project_description', models.TextField()),
                ('desired_timeline', models.CharField(choices=[('immediate', 'Immediate (Within 30 Days)'), ('1_to_3_months', '1 - 3 Months'), ('3_to_6_months', '3 - 6 Months'), ('planning', 'Exploring / Planning Phase')], default='1_to_3_months', max_length=30)),
                ('budget_range', models.CharField(choices=[('under_5k', 'Under $5,000 / ₦5,000,000'), ('5k_to_15k', '$5,000 - $15,000'), ('15k_to_50k', '$15,000 - $50,000'), ('50k_plus', '$50,000+'), ('custom', 'To Be Defined / Grant Funded')], default='5k_to_15k', max_length=30)),
                ('current_system_details', models.TextField(blank=True)),
                ('brief_attachment_url', models.URLField(blank=True, max_length=500)),
                ('privacy_consent_recorded', models.BooleanField(default=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Project inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicePillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('summary', models.TextField()),
                ('problem_addressed', models.TextField()),
                ('capabilities', models.JSONField(default=list, help_text='List of specific deliverables/capabilities')),
                ('engagement_types', models.TextField(help_text='e.g. Full build, Modernization, Architecture audit')),
                ('delivery_process', models.JSONField(default=list, help_text='List of process stages (Discover, Define, Design, etc.)')),
                ('faqs', models.JSONField(default=list, help_text="Service-specific FAQs: [{'q': '...', 'a': '...'}]")),
                ('cta_label', models.CharField(default='Discuss Your Project', max_length=100)),
                ('cta_link', models.CharField(default='/consultation', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('client_name', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('service_type', models.CharField(choices=[('maintenance', 'Routine Maintenance & Health Checks'), ('bug_incident', 'Bug / System Outage'), ('enhancement', 'Feature Enhancement / Expansion'), ('optimization', 'Performance & Security Optimization')], default='bug_incident', max_length=30)),
                ('urgency', models.CharField(choices=[('low', 'Low - General Question'), ('medium', 'Medium - Minor Issue / Non-Blocking'), ('high', 'High - Core Feature Degraded'), ('critical', 'Critical - Complete Outage / Emergency')], default='medium', max_length=20)),
                ('affected_system', models.CharField(help_text='e.g. TIIPE Web Portal, Client ERP', max_length=200)),
                ('issue_description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New Request'), ('in_progress', 'Under Investigation / In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('topic_category', models.CharField(choices=[('web_mobile', 'Web & Mobile Application Engineering'), ('data_ai', 'Data Analytics, Engineering & Applied AI'), ('cloud_devops', 'Cloud Infrastructure & DevOps'), ('business_systems', 'Business Systems Implementation & CRM'), ('digital_foundations', 'Digital Literacy & Productivity Foundations')], default='web_mobile', max_length=40)),
                ('level', models.CharField(choices=[('beginner', 'Foundational / Beginner'), ('intermediate', 'Intermediate / Career Transition'), ('advanced', 'Advanced / Senior Specialization')], default='beginner', max_length=30)),
                ('format', models.CharField(choices=[('live_online', 'Live Online Cohort'), ('in_person', 'In-Person Workshop / BootCamp'), ('hybrid', 'Hybrid (Online + In-Person)'), ('self_paced', 'Self-Paced with Mentor Reviews')], default='live_online', max_length=30)),
                ('duration_weeks', models.PositiveIntegerField(default=8)),
                ('summary', models.TextField()),
                ('target_audience', models.CharField(max_length=255)),
                ('learning_outcomes', models.JSONField(default=list)),
                ('prerequisites', models.TextField(blank=True)),
                ('syllabus_modules', models.JSONField(default=list, help_text='List of curriculum modules and weekly topics')),
                ('hands_on_projects', models.JSONField(default=list, help_text='List of portfolio projects built during training')),
                ('certificate_details', models.CharField(default='Assessed Credential and Verified Digital Certificate', max_length=255)),
                ('price_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_currency', models.CharField(default='USD', max_length=10)),
                ('is_enrollment_open', models.BooleanField(default=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['topic_category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquirer_type', models.CharField(choices=[('individual', 'Individual Learner'), ('corporate', 'Corporate / Institutional Cohort')], default='individual', max_length=20)),
                ('inquirer_name', models.CharField(max_length=150)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_or_whatsapp', models.CharField(max_length=50)),
                ('training_topic_custom', models.CharField(blank=True, max_length=200)),
                ('participant_count', models.PositiveIntegerField(default=1)),
                ('desired_outcome', models.TextField()),
                ('preferred_format', models.CharField(default='live_online', max_length=30)),
                ('target_start_date', models.DateField(blank=True, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='novatrix_services.trainingcourse')),
            ],
            options={
                'verbose_name_plural': 'Training inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_name', models.CharField(help_text="e.g. 'Cohort 2026-Q3'", max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('schedule_description', models.CharField(help_text="e.g. 'Tuesdays & Thursdays 6pm - 8pm WAT'", max_length=200)),
                ('max_capacity', models.PositiveIntegerField(default=30)),
                ('enrolled_count', models.PositiveIntegerField(default=0)),
                ('is_registration_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='novatrix_services.trainingcourse')),
            ],
        ),
    ]
