# Generated by Django 4.2.30 on 2026-09-09 07:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role_title', models.CharField(help_text='e.g. President, Board Chair, Treasurer', max_length=150)),
                ('bio', models.TextField()),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('linkedin_url', models.URLField(blank=True, max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(default='Community Gathering', max_length=100)),
                ('location', models.CharField(default='Online / New Rochelle, NY', max_length=255)),
                ('event_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('registration_url', models.URLField(blank=True, max_length=500)),
                ('banner_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(default='General', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='GovernanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('bylaws', 'Corporate Bylaws'), ('conflict_of_interest', 'Conflict of Interest & Recusal Standards'), ('501c3_status', '501(c)(3) IRS Determination Letter'), ('form_990', 'Form 990 Tax Return'), ('annual_report', 'Annual Impact & Financial Report'), ('ethics_charter', 'Code of Ethics & Public Benefit Charter'), ('other', 'General Governance Policy')], default='bylaws', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('file_url', models.URLField(help_text='S3 / Spaces document URL', max_length=500)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('published_year', models.IntegerField(default=2026)),
                ('is_public', models.BooleanField(default=True)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_year', 'doc_type'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_identifier', models.CharField(default='home', help_text="e.g. 'home', 'programs', 'services'", max_length=50)),
                ('headline', models.CharField(max_length=255)),
                ('subheadline', models.TextField()),
                ('cta_primary_text', models.CharField(blank=True, max_length=100)),
                ('cta_primary_link', models.CharField(blank=True, max_length=255)),
                ('cta_secondary_text', models.CharField(blank=True, max_length=100)),
                ('cta_secondary_link', models.CharField(blank=True, max_length=255)),
                ('cta_tertiary_text', models.CharField(blank=True, max_length=100)),
                ('cta_tertiary_link', models.CharField(blank=True, max_length=255)),
                ('background_image_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
        migrations.CreateModel(
            name='ImpactMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('value', models.CharField(help_text="e.g. '500', '10,000', '100%'", max_length=50)),
                ('suffix', models.CharField(blank=True, help_text="e.g. '+', 'K', '%'", max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='MediaBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('adietalk_radio', 'AdieTalk Radio Live/Stream'), ('podcast', 'TIIPE Podcast Episode'), ('video', 'Video Presentation / Feature'), ('interview', 'Community & Expert Interview')], default='podcast', max_length=30)),
                ('episode_number', models.PositiveIntegerField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('stream_url', models.URLField(help_text='Direct MP3 / Stream link', max_length=500)),
                ('external_embed_url', models.URLField(blank=True, help_text='YouTube, Spotify or SoundCloud embed', max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('listen_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('header', 'Header Primary Navigation'), ('footer_quick', 'Footer Quick Links'), ('footer_services', 'Footer Services / Programs'), ('footer_legal', 'Footer Legal & Governance')], default='header', max_length=30)),
                ('items', models.JSONField(default=list, help_text="List of items: [{'label': 'Home', 'path': '/', 'order': 1}]")),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicBenefitStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(blank=True, max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150)),
                ('author_title', models.CharField(blank=True, max_length=150)),
                ('author_organization', models.CharField(blank=True, max_length=150)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('host_or_speaker', models.CharField(max_length=255)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('registration_link', models.URLField(blank=True, max_length=500)),
                ('meeting_link', models.URLField(blank=True, max_length=500)),
                ('recording_url', models.URLField(blank=True, max_length=500)),
                ('is_completed', models.BooleanField(default=False)),
                ('attendee_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('summary', models.TextField()),
                ('body', models.TextField(help_text='Markdown or HTML formatted article content')),
                ('author_name', models.CharField(default='Editorial Team', max_length=150)),
                ('featured_image_url', models.URLField(blank=True, max_length=500)),
                ('read_time_minutes', models.PositiveIntegerField(default=5)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='cms.articlecategory')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
