# Generated by Django 4.2.30 on 2026-09-09 07:10

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_id', models.CharField(default=uuid.uuid4, max_length=60, unique=True)),
                ('donor_name', models.CharField(max_length=150)),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_phone', models.CharField(blank=True, max_length=50)),
                ('donor_address', models.TextField(blank=True, help_text='Used for 501(c)(3) tax receipt generation')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('frequency', models.CharField(choices=[('one_time', 'One-Time Contribution'), ('monthly', 'Monthly Recurring Giving')], default='one_time', max_length=20)),
                ('fund_allocation', models.CharField(choices=[('general_fund', 'TIIPE General Operations & Impact Fund'), ('education_tutoring', 'Academic Tutoring & Student Learning Kits'), ('public_health', 'Public Health & Maternal Literacy Outreach'), ('civic_outreach', 'Civic Engagement & Policy Research')], default='general_fund', max_length=40)),
                ('gateway', models.CharField(choices=[('stripe', 'Stripe Payments'), ('paypal', 'PayPal Gateway'), ('paystack', 'Paystack')], default='stripe', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=150, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('successful', 'Completed & Verified'), ('failed', 'Payment Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('gateway_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_receipt_pdf_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(max_length=100)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_credited_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_organization', models.CharField(blank=True, max_length=150)),
                ('line_items', models.JSONField(default=list, help_text="[{'description': '...', 'quantity': 1, 'unit_price': 100}]")),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('void', 'Void')], default='issued', max_length=20)),
                ('pdf_download_url', models.URLField(blank=True, max_length=500)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_purpose', models.CharField(choices=[('course_enrollment', 'Training Course Enrollment'), ('corporate_training', 'Corporate Cohort Training'), ('software_milestone', 'Custom Software Development Milestone'), ('support_retainer', 'Support & Maintenance Retainer')], default='course_enrollment', max_length=40)),
                ('gateway', models.CharField(default='stripe', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=30)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('is_processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
